### ISSUE TITLE
SPI Interface - Can not connect to Server

### ISSUE THREAD

**Issue by cknivu** [acconeer/acconeer-python-exploration#105]
**Describe the bug**
I'm trying to connect the XM112 via the SPI Interface in the GUI.
XM112 is connected to USB2 and USB1.

I get the following Error:

**Traceback**
```
Exception raised in SPI communication process:

Traceback (most recent call last):
  File "C:\Users\Kochc\AppData\Roaming\Python\Python310\site-packages\acconeer_exptool-3.16.1-py3.10.egg\acconeer\exptool\clients\reg\client.py", line 628, in run
    self._run()
  File "C:\Users\Kochc\AppData\Roaming\Python\Python310\site-packages\acconeer_exptool-3.16.1-py3.10.egg\acconeer\exptool\clients\reg\client.py", line 646, in _run
    ret = getattr(self, cmd)(*cmd_args)
  File "C:\Users\Kochc\AppData\Roaming\Python\Python310\site-packages\acconeer_exptool-3.16.1-py3.10.egg\acconeer\exptool\clients\reg\client.py", line 757, in read_buf_raw
    return self.dev.spi_master_single_read(size)
  File "C:\Users\Kochc\AppData\Roaming\Python\Python310\site-packages\acconeer_exptool-3.16.1-py3.10.egg\acconeer\exptool\libft4222.py", line 323, in spi_master_single_read
    assert size_transferred.value == num_bytes
AssertionError
```

**Environment :**
 - Host OS: Windows 10
 - Acconeer hardware:XM112 + XB112
 - Acconeer software version: RSS v2.10.0
 - Exploration version: v3.16.1

**Comment by AndersBuhl** [comment]
Hi,

This is an issue related to the latest Acconeer Software Version. The issue will be fixed in the next software release for XM112.

BR,
Anders
