### ISSUE TITLE
 "Failed to get_next" when loading data from a121 examples

### ISSUE THREAD

**Issue by thedevleon** [acconeer/acconeer-python-exploration#134]
**Describe the bug**
Trying to load any of the data from the other a121 repos results in a error shown "Failed to get_next".

Data I tried to load
- https://github.com/acconeer/acconeer-a121-gesture-control/tree/main/data
- https://github.com/acconeer/acconeer-a121-carpet-detection/tree/main/data
- https://github.com/acconeer/acconeer-a121-grass-detection/tree/main/data

**To reproduce**
1. Install exploration tool `python -m pip install --upgrade "acconeer-exptool[app]"`
2. Start exploration tool `python -m acconeer.exptool.app`
3. Click on "Load from file" and select a .h5 file

**Traceback**
```
Traceback (most recent call last):
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/a121/algo/_plugins/_a121.py", line 106, in idle
    self.get_next()
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/a121/algo/_plugins/processor/backend_plugin.py", line 310, in get_next
    result = self.client.get_next()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/app/new/backend/_application_client.py", line 71, in get_next
    stats = self._rate_stats_calc.update(result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/app/new/backend/_rate_calc.py", line 109, in update
    jitter_s = statistics.pstdev(self.tick_diffs) / self.ticks_per_second
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leon/anaconda3/envs/radar/lib/python3.12/statistics.py", line 992, in pstdev
    return _float_sqrt_of_frac(mss.numerator, mss.denominator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leon/anaconda3/envs/radar/lib/python3.12/statistics.py", line 428, in _float_sqrt_of_frac
    q = (n.bit_length() - m.bit_length() - _sqrt_bit_width) // 2
         ^^^^^^^^^^^^
AttributeError: 'numpy.int64' object has no attribute 'bit_length'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/app/new/backend/_backend.py", line 138, in process_program
    model_wants_to_idle = model.idle()
                          ^^^^^^^^^^^^
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/app/new/backend/_model.py", line 44, in idle
    return self.backend_plugin.idle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leon/Desktop/dev/radar/AccoNeer/venv/lib/python3.12/site-packages/acconeer/exptool/a121/algo/_plugins/_a121.py", line 116, in idle
    raise HandledException("Failed to get_next") from exc
acconeer.exptool.app.new._exceptions.HandledException: Failed to get_next

```

**Installed packages**
If applicable, add a list of installed packages. Obtain the list with `pip freeze`.

**Screenshots**
![image](https://github.com/acconeer/acconeer-python-exploration/assets/12817042/1c7a8fd2-bca4-4784-a75a-c23169a91115)

**Environment (please complete the following information):**
 - Host OS: Ubuntu 22.04.03 LTS
 - Acconeer hardware: None (so far)
 - Acconeer software version: the latest
 - Exploration version: the latest

**Comment by thedevleon** [comment]
Fixed by downgrading the exptool.
> pip install acconeer-exptool==6.0.5
