### ISSUE TITLE
Connection to server successful, first measurement apparently, also, but then, it fails.

### ISSUE THREAD

**Issue by Huwyler** [acconeer/acconeer-python-exploration#154]
Ubuntu 22.04
Exploration tool client (ET): 7.12.1
Server(RSS): a121-v1.8.0
Python: 3.10.12
Hardware: Sparkfun XM125 breakout board

I can download the server to the STM32, the exploration tool successfully connects, but when I start Sparse IQ (or any other tool), I get assumably one sample (I see reasonable data), but then, I get the following error message.

I don't assume this is related to the SparkFun hardware. If there was any discrepancy to the XE125, I could not connect in the first place. Also, the log "RuntimeError: Cannot decode header bytearray(b'"result_info":[[{"tick":11772,"data_saturated":false,"temperature":30,"calibration_needed":false,"frame_delayed":false}]],"stat":"ok","payload_size":192}\n')" Doesn't look like a hardware issue to me

```

Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/_core/communication/message_stream.py", line 86, in _get_stream
    header: dict[str, t.Any] = json.loads(header_in_bytes)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 14 (char 13)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/a121/algo/_plugins/_a121.py", line 118, in idle
    self.get_next()
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/a121/algo/_plugins/processor/backend_plugin.py", line 264, in get_next
    result = self.client.get_next()
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/backend/_application_client.py", line 95, in get_next
    result = self._wrapped_client.get_next()
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/a121/_core/communication/exploration_client.py", line 276, in get_next
    result_message = self._server_stream.wait_for_message(a121_messages.ResultMessage)
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/_core/communication/message_stream.py", line 64, in wait_for_message
    for message in self._stream:
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/_core/communication/message_stream.py", line 88, in _get_stream
    self._error_callback(RuntimeError(f"Cannot decode header {header_in_bytes!r}"))
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/a121/_core/communication/exploration_client.py", line 136, in _close_before_reraise
    raise exception
RuntimeError: Cannot decode header bytearray(b'"result_info":[[{"tick":11772,"data_saturated":false,"temperature":30,"calibration_needed":false,"frame_delayed":false}]],"stat":"ok","payload_size":192}\n')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/backend/_backend.py", line 207, in process_generator
    model_wants_to_idle = model.idle()
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/app/new/backend/_model.py", line 52, in idle
    return self.backend_plugin.idle()
  File "/home/simon/.local/lib/python3.10/site-packages/acconeer/exptool/a121/algo/_plugins/_a121.py", line 129, in idle
    raise HandledException(msg) from exc
acconeer.exptool.app.new._exceptions.HandledException: Failed to get_next
```

**Comment by Huwyler** [comment]
Sorry, just looked into other issues and got the hint that indeed, the SparkFun board has some HW issues. Setting the baud rate to 115200 fixes the issue
