### ISSUE TITLE
issue with surface velocity example 

### ISSUE THREAD

**Issue by nguyenxuanlamiwe** [acconeer/acconeer-python-exploration#155]
hello acconeer 

I have issue with the example of surface velocity. Once time I input the surface distance as 20m, it came with Error. After that, every time I start this application, this error always come. Please give me a help !
![github_error](https://github.com/user-attachments/assets/e1121268-4153-4b2d-af78-d544b16d3ef2)

Traceback (most recent call last):
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\app\new\ui\misc.py", line 58, in context
    yield
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\app\new\pluginbase\ui_plugin_base.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\app\new\pluginbase\ui_plugin_base.py", line 48, in wrapper
    raise e
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\app\new\pluginbase\ui_plugin_base.py", line 40, in wrapper
    return f(instance, *args, **kwargs)
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\a121\algo\surface_velocity\_example_app_plugin.py", line 568, in on_backend_state_update
    self.range_helper.set_data(ExampleApp._get_sensor_config(state.config).subsweep)
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\a121\algo\surface_velocity\_example_app.py", line 264, in _get_sensor_config
    prf=select_prf(end_point, profile),
  File "G:\GREECOTECH\radar sensor\portable\tools\python-3.9.10-embed-amd64\lib\site-packages\acconeer\exptool\a121\algo\_utils.py", line 450, in select_prf
    return sorted(viable_prfs, key=lambda prf: prf.frequency)[-1]
IndexError: list index out of range

**Comment by AndersBuhl** [comment]
Hi,
This is an error in the validation of the config. To get rid of the issue temporarily use '--purge-config' to clean the cache of the application. This will be fixed in the next release.

BR,
Anders
