### ISSUE TITLE
Exploration GUI does not connect to XM112 

### ISSUE THREAD

**Issue by wangxiatao** [acconeer/acconeer-python-exploration#25]
**Describe the bug**
I guess I'm experiencing almost the same as the other two bug reports, since it's not the same hardware I thought I'll post a new thread here. Basically I have a setup with XM112 and XB112, serial port shows up in the system, I could use other serial tools to connect (HTerm on Windows 10, and pyserial on MacOS), but not the exploration GUI. Same situation on both OS.

Now you have three bug reports, can you try to reproduce on your end using a fresh PC? I'm sure it's quite easy to see the problem.

**To reproduce**
Plug in, run the GUI, try to connect serial port, get the error.

**Traceback from GUI**
Traceback (most recent call last):
  File "gui/main.py", line 1435, in connect_to_server
    info = self.client.connect()
  File "/Users/tao/Library/Python/3.7/lib/python/site-packages/acconeer/exptool/clients/base.py", line 24, in connect
    info = self._connect()
  File "/Users/tao/Library/Python/3.7/lib/python/site-packages/acconeer/exptool/clients/reg/client.py", line 185, in _connect
    self._link.connect()
  File "/Users/tao/Library/Python/3.7/lib/python/site-packages/acconeer/exptool/clients/links.py", line 229, in connect
    raise LinkError("failed to connect, see traceback from serial process")
acconeer.exptool.clients.links.LinkError: failed to connect, see traceback from serial process

**Traceback from terminal
21:44:32.060 | DEBUG   | Process-2        | acconeer.exptool.clients.links       | serial communication process started
21:44:32.068 | DEBUG   | MainProcess      | acconeer.exptool.clients.links       | connect - flow event was set
21:44:32.069 | DEBUG   | MainProcess      | acconeer.exptool.clients.links       | connect - error event was set
Exception raised in serial process:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/serial/serialposix.py", line 310, in _reconfigure_port
    fcntl.flock(self.fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tao/Library/Python/3.7/lib/python/site-packages/acconeer/exptool/clients/links.py", line 338, in serial_process_program
    _serial_process_program(port, baud, recv_q, send_q, flow_event, error_event)
  File "/Users/tao/Library/Python/3.7/lib/python/site-packages/acconeer/exptool/clients/links.py", line 352, in _serial_process_program
    ser = serial.Serial(port=port, baudrate=baud, timeout=0, exclusive=True)
  File "/usr/local/lib/python3.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/local/lib/python3.7/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/local/lib/python3.7/site-packages/serial/serialposix.py", line 312, in _reconfigure_port
    raise SerialException(msg.errno, "Could not exclusively lock port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 35] Could not exclusively lock port /dev/cu.usbserial-00352: [Errno 35] Resource temporarily unavailable

**Screenshots**

**Environment (please complete the following information):**
 - Host OS: Windows 10, MacOS
 - Acconeer hardware: XM112 + XB112
 - Acconeer software version: 2.0.0
 - Exploration version: Latest

**Comment by wangxiatao** [comment]
OK, after re-flashing a new firmware the connection issue seems to be solved. But the connection is quite unstable. Need more test to have concrete evidence, the serial connection stability seems to be a culprit in both cases.
