### ISSUE TITLE
GUI doesn't connect with COM port

### ISSUE THREAD

**Issue by MuthukumarEC** [acconeer/acconeer-python-exploration#40]
Hello,
I try to connect my MX122 module in GUI script it provide some error as below i mentioned

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\reg\client.py", line 175, in _connect
    self._handshake()
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\reg\client.py", line 403, in _handshake
    self._link.recv_until(exp_frame)
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\links.py", line 155, in recv_until
    raise LinkError("recv timeout")
acconeer.exptool.clients.links.LinkError: recv timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui/main.py", line 1484, in connect_to_server
    info = self.client.connect()
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\base.py", line 29, in connect
    info = self._connect()
  File "C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\acconeer\exptool\clients\reg\client.py", line 177, in _connect
    raise ClientError("could not connect, no response") from e
acconeer.exptool.clients.base.ClientError: could not connect, no response

**Comment by erikmansson** [comment]
I most cases when unable to connect in this way, the firmware isn't flashed properly. Please try flashing again and get back to us.

**Comment by MuthukumarEC** [comment]
i fully flashed the module and update DFU in v2.2.1 and run the module. It show same com port error

**Comment by pthorell** [comment]
Did you flash the module using nrfutil accoring to the instructions on page 8 in the getting started guide (https://developer.acconeer.com/download/getting-started-guide-xm122-pdf/) ?

**Comment by MuthukumarEC** [comment]
I try to flash module via command i had error as bellow

Traceback (most recent call last):
  File "nordicsemi\__main__.py", line 1464, in <module>
  File "click\core.py", line 764, in __call__
  File "click\core.py", line 717, in main
  File "click\core.py", line 1137, in invoke
  File "click\core.py", line 1137, in invoke
  File "click\core.py", line 956, in invoke
  File "click\core.py", line 555, in invoke
  File "nordicsemi\__main__.py", line 1042, in serial
  File "nordicsemi\__main__.py", line 956, in do_serial
  File "nordicsemi\dfu\dfu.py", line 129, in dfu_send_images
  File "nordicsemi\dfu\dfu.py", line 90, in _dfu_send_image
  File "nordicsemi\dfu\dfu_transport_serial.py", line 214, in open
pc_ble_driver_py.exceptions.NordicSemiException: No ping response after opening COM port
[4228] Failed to execute script __main__

**Comment by pthorell** [comment]
Make sure that you have put the module in DFU mode (see page 7 in the getting started guide) and check that you are using the right COM port.

**Comment by erikmansson** [comment]
Closing this due to inactivity. Please feel free to reopen again if needed.
