### ISSUE TITLE
Incompatibility with pyqtgraph 0.12.2

### ISSUE THREAD

**Issue by GuidoBartoli** [acconeer/acconeer-python-exploration#88]
The included `requirements.txt` installs the latest 0.12 version of `pyqtgraph` which currently is 0.12.2. Launching the GUI with that version produces the following error when some specific plots are required (i.e. time/depth plots with _Envelope_ service) and nothing is drawn on those axes:

```
Traceback (most recent call last):
  File "/home/bartoli/.virtualenvs/acc/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 834, in paint
    self.render()
  File "/home/bartoli/.virtualenvs/acc/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 561, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/bartoli/.virtualenvs/acc/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1401, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
```

Manually installing **pyqtgraph 0.12.1** solves this issue, so I think that requirements should specify `pyqtgraph=0.12.1` instead of `pyqtgraph=0.12.*` (at least as a workaround until the GUI code is not updated to support the newer version).

**Comment by elinayrli** [comment]
Thanks for the report. We've confirmed the issue and fixed it in the referenced commit.
