### ISSUE TITLE
No git repository was found at https://github.com/acconeer/acconeer-python-exploration.git

### ISSUE THREAD

**Issue by lukegalea16** [acconeer/acconeer-python-exploration#99]
I downloaded the **Quickstart for Windows Tool** and when I run the **update.bat** I am getting the following output

"Traceback (most recent call last):
  File ".\tools\update.py", line 41, in <module>
    main()
  File ".\tools\update.py", line 32, in main
    porcelain.clone(repo_addr, target=repo_dir)
  File "C:\Users\lu\Downloads\portable_exploration_tool\tools\python-3.7.3-embed-amd64\lib\site-packages\dulwich\porcelain.py", line 444, in clone
    with open_repo_closing(source) as r:
  File "C:\Users\lu\Downloads\portable_exploration_tool\tools\python-3.7.3-embed-amd64\lib\site-packages\dulwich\porcelain.py", line 215, in open_repo_closing
    return closing(Repo(path_or_repo))
  File "C:\Users\lu\Downloads\portable_exploration_tool\tools\python-3.7.3-embed-amd64\lib\site-packages\dulwich\repo.py", line 1060, in __init__
    "No git repository was found at %(path)s" % dict(path=root)
dulwich.errors.NotGitRepository: No git repository was found at https://github.com/acconeer/acconeer-python-exploration.git

Update failed"

I cannot run the tool.

**Comment by vackraetraed** [comment]
​Resolved in email, there is an issue with a recent dulwich commit.
Might have to update update.py to set a specific dulwich version.
